{
    "name" : "ecartes_pbg",
    "version" : "15.0",
    "category": "Uncategorized",
    "summary": "ecartes_pbg",
    "description": "ecartes_pbg",
    'author': 'Virtual-X Solution',
    'company': 'Virtual-X Solution',
    "depends": ['base','ecartes_crm','sale','web_notify'],
    "data": [
        'security/res_groups.xml',
        "security/ir.model.access.csv",
        'wizard/return_pbg_view.xml',
        'data/mail_data.xml',
        'wizard/issue.xml',
        'wizard/reject_reason_view.xml',
        'data/mail_template.xml',
        'data/pbg_validity_check_cron.xml',
        'data/rule.xml',
        "views/pbg_details_view.xml",
        "report/report.xml",
        "report/pbg_report_template.xml",
    ],
    'license': 'LGPL-3',
} 
